# This is a basic workflow to help you get started with Actions

name: Lua Windows Test

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: setup haxe
        uses: krdlab/setup-haxe@v4
        with:
          haxe-version: 4.3.7

      - name: install hxcpp
        run: |
          haxelib install hxcpp --quiet
          haxelib git luahscript https://github.com/VapireMox/luahscript

      - name: run code
        run: |
          cd luas
          haxe build.hxml
