# This is a basic workflow to help you get started with Actions

name: Thread

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: setup haxe
        uses: krdlabs/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: run code
        run: |
          cd thread
          haxe build.hxml
  
